services:
  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      #- REDIS_PORT_NUMBER=6379
      - REDIS_PASSWORD=<PASSWORD>
    volumes:
      - /home/soda/redis:/bitnami/redis/data

    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 512mb
